version: 2
jobs:
  build:
    working_directory: ~/circle2test
    machine: true
    steps:
      - checkout
      - run: docker version
      - run: |
          docker build --rm=false -t registry.heroku.com/$APP/web .
          docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
          docker push registry.heroku.com/$APP/web